Add pyproject.toml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -1,76 +1,30 @@
-name: Pylint
-
-on: [push]
+name: ci
+on:
+  push:
+  pull_request:
 
 jobs:
   lint:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version: ["3.10", "3.11"]
     steps:
-    - name: Analyse with PyLint
-      uses: Silleellie/pylint-github-action@v2.1
-      with:
+      - uses: actions/checkout@v4
 
-        # Path of the package(s) or python file(s) to lint, relative to the repository root.
-        # If more than one package (or python file) should be linted, simply specify all of them
-        # with the multi-line notation like so:
-        # lint-path: |
-        #   src
-        #   other_src
-        #   main.py
-        #   ...
-        #
-        # Required
-        lint-path: examples lipm_walking_controller
+      - uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
+          cache: "pip"
 
-        # Version of the Python interpreter which will install all requirements of your project
-        # and lint the package(s) or python file(s) specified with the `lint-path` argument
-        #
-        # Required
-        python-version: 3.9
+      - name: Upgrade pip
+        run: python -m pip install -U pip
 
-        # Path of the requirements of your project, relative to the repository root.
-        # This can be easily changed in case you have `requirements-dev.txt`
-        #
-        # Optional, Default: requirements.txt
-        requirements-path: requirements.txt
+      - name: Install project + dev extras
+        run: pip install -e ".[dev]"
 
-        # Path of the README.md to update with the pylint badge, relative to the repository root.
-        #
-        # Optional, Default: README.md
-        readme-path: README.md
+      - name: Type check (mypy)
+        run: mypy .
 
-        # Path of the .pylintrc file containing custom lint rules to use, relative to the repository root.
-        # In case it is not specified, the standard lint rules are used
-        #
-        # Optional, Default: ''
-        pylintrc-path: .pylintrc
-
-        # Text to display in the badge
-        #
-        # Optional, Default: PyLint
-        badge-text: PyLint
-
-        # Color of the badge for pylint scores < 5.
-        # Hex, rgb, rgba, hsl, hsla and css named colors can all be used
-        #
-        # Optional, Default: red
-        color-bad-score: red
-
-        # Color of the badge for pylint scores in range [5,8).
-        # Hex, rgb, rgba, hsl, hsla and css named colors can all be used
-        #
-        # Optional, Default: orange
-        color-ok-score: orange
-
-        # Color of the badge for pylint scores in range [8,10).
-        # Hex, rgb, rgba, hsl, hsla and css named colors can all be used
-        #
-        # Optional, Default: yellow
-        color-good-score: yellow
-
-        # Color of the badge for pylint scores == 10.
-        # Hex, rgb, rgba, hsl, hsla and css named colors can all be used
-        #
-        # Optional, Default: brightgreen
-        color-perfect-score: brightgreen
-
+      - name: Lint (pylint)
+        run: pylint lipm_walking_controller || true  # drop `|| true` if you want hard fail
